### ISSUE TITLE
HELP ME

### ISSUE THREAD

**Issue by floconacs** [liamhoganson/SigCreator#1]
Hello I allow myself to open this issue to ask you advice. I am currently developing the same script as you but I am blocked at this point (attachment).
It seems that the "next" button is an ifram and I have no idea how to get Selenium to press it. If you can help me it would be very nice.
Thank you very much for your help.

![image](https://user-images.githubusercontent.com/96012547/187234321-50497f87-62fb-436b-8c90-30dfdb06e046.png)

**Comment by liamhoganson** [comment]
My script does not contain the use of Selenium nor is it a web scraper. However, I have worked with Selenium in the past. I would use the Xpath of the 'next' button on that webpage for it to click. See here: https://www.tutorialspoint.com/how-to-click-button-selenium-python#:~:text=We%20can%20click%20a%20button,is%20represented%20by%20button%20tagname.
